name: conform
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - fpocket
  - vina
  - openbabel
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - biopython
  - mdanalysis
  - pyyaml
  - pydantic
  - pytest
  - streamlit
  - py3dmol
